name: Execute Customer Loyalty Agent

on:
  push:
    paths:
      - src/app/agents/customerLoyaltyAgent_initializer.py
      - src/app/tools/discountLogic.py
      - src/prompts/CustomerLoyaltyAgentPrompt.txt

jobs:
  run-customer-loyalty-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Login via Azure CLI
        uses: azure/login@v2.1.1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-ai-projects
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run customer loyalty agent initializer
        run: python src/app/agents/customerLoyaltyAgent_initializer.py
